const actions = {

    CATEGORY: "CATEGORY",
    CATEGORIES: "CATEGORIES",

    COMMENT: "COMMENT",
    COMMENTS: "COMMENTS",
    ADD_COMMENT: "ADD_COMMENT",
    EDIT_COMMENT: "COMMENT_VOTE",

    POST: "POST",
    POSTS: "POSTS",
    ADD_POST: "ADD_POST",
    GET_POST: "GET_POST",
    EDIT_POST: "EDIT_POST",
    REMOVE_POST: "REMOVE_POST",
    POST_VOTE: "POST_VOTE",
    FILTER_POSTS: "FILTER_POSTS",

    // Sorting
    MOST_RECENT_POSTS: "MOST_RECENT_POSTS",
    MOST_POPULAR_POSTS: "MOST_POPULAR_POSTS",
    MOST_RECENT_COMMENTS: "MOST_RECENT_COMMENTS",
    MOST_POPULAR_COMMENTS: "MOST_POPULAR_COMMENTS"
  }
  export default actions;