const actions = {  
    CREATE_POST: "CREATE_POST",
    EDIT_POST: "EDIT_POST",
    REMOVE_POST: "REMOVE_POST",
    UPVOTE_POST: "UPVOTE_POST",
    DOWNVOTE_POST: "DOWNVOTE_POST",
    // Comments
    CREATE_COMMENT: "CREATE_COMMENT",
    EDIT_COMMENT: "EDIT_COMMENT",
    UPVOTE_COMMENT: "UPVOTE_COMMENT",
    DOWNVOTE_COMMENT: "DOWNVOTE_COMMENT",
    // Sorting
    MOST_RECENT: "MOST_RECENT",
    MOST_POPULAR: "MOST_POPULAR"
  }
  export default actions;