const actions = {  
    CATEGORY: "CATEGORY",
    UPDATE_POST_FROM_API: "UPDATE_POST_FROM_API",

    CREATE_POST: "CREATE_POST",
    EDIT_POST: "EDIT_POST",
    REMOVE_POST: "REMOVE_POST",
    UPVOTE_POST: "UPVOTE_POST",
    DOWNVOTE_POST: "DOWNVOTE_POST",
    // Comments
    CREATE_COMMENT: "CREATE_COMMENT",
    EDIT_COMMENT: "EDIT_COMMENT",
    UPVOTE_COMMENT: "UPVOTE_COMMENT",
    DOWNVOTE_COMMENT: "DOWNVOTE_COMMENT",
    // Sorting
    MOST_RECENT_POSTS: "MOST_RECENT_POSTS",
    MOST_POPULAR_POSTS: "MOST_POPULAR_POSTS",
    MOST_RECENT_COMMENTS: "MOST_RECENT_COMMENTS",
    MOST_POPULAR_COMMENTS: "MOST_POPULAR_COMMENTS"
  }
  export default actions;