const actions = {
  CATEGORY: "CATEGORY",
  CATEGORIES: "CATEGORIES",

  COMMENT: "COMMENT",
  COMMENTS: "COMMENTS",
  ADD_COMMENT: "ADD_COMMENT",
  EDIT_COMMENT: "EDIT_COMMENT",
  COMMENT_VOTE: "COMMENT_VOTE",
  REMOVE_COMMENT: "REMOVE_COMMENT",
  CHANGE_COMMENT: "CHANGE_COMMENT",
  PREPARE_COMMENT: "PREPARE_COMMENT",
  CLEAR_COMMENT: "CLEAR_COMMENT",
  UPDATE_COMMENTS: "UPDATE_COMMENTS",

  POST: "POST",
  POSTS: "POSTS",
  ADD_POST: "ADD_POST",
  NEW_POST: "NEW_POST",
  GET_POST: "GET_POST",
  EDIT_POST: "EDIT_POST",
  REMOVE_POST: "REMOVE_POST",
  POST_VOTE: "POST_VOTE",
  FILTER_POSTS: "FILTER_POSTS",
  PREPARE_POST: "PREPARE_POST",


  // Sorting
  MOST_RECENT_POSTS: "MOST_RECENT_POSTS",
  MOST_POPULAR_POSTS: "MOST_POPULAR_POSTS",
  MOST_RECENT_COMMENTS: "MOST_RECENT_COMMENTS",
  MOST_POPULAR_COMMENTS: "MOST_POPULAR_COMMENTS"
}
export default actions;